title: COL 106: Data Structures and Algorithms (Jan-Apr 2025)
tagline: A Jekyll template for course websites
description: A modern, highly customizable, responsive Jekyll template for course websites
author: Nikhil Balaji and Srikanta Bedathur
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://col106iitd.github.io/' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

